# -*- coding: utf-8 -*-
# Generated by Django 3.1.2 on 2020-10-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('exp_type', models.CharField(max_length=20)),
            ],
        ),
    ]
